### ISSUE TITLE
When adding pollMs agora throws an error.

### ISSUE THREAD

**Issue by arch-btw** [HP4k1h5/agora#13]
**Describe the bug**

Whenever I add PollMs it throws this error:

```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at shapeQuote (file:///home/archbtw/agora/src/shape/shapeIex.js:71:17)
    at Object.buildQuoteList [as uiFn] (file:///home/archbtw/agora/src/ui/iex/quote.js:32:10)
    at up (file:///home/archbtw/agora/src/ui/update.js:96:29)
    at update (file:///home/archbtw/agora/src/ui/update.js:70:11)
    at file:///home/archbtw/agora/src/index.js:46:17
    at Array.map (<anonymous>)
    at Array.<anonymous> (file:///home/archbtw/agora/src/index.js:43:31)
    at Carousel.move (/home/archbtw/agora/node_modules/@hp4k1h5/blessed-contrib/lib/layout/carousel.js:16:28)
    at Carousel.start (/home/archbtw/agora/node_modules/@hp4k1h5/blessed-contrib/lib/layout/carousel.js:59:8)
```

**To Reproduce**

Run agora with this config, but with and without pollMs

```
{
  "IEX_PUB_KEY": "",
  "APCA_API_KEY_ID": "",
  "APCA_API_SECRET_KEY": "",
  "alpacaAccountType": "paper",
  
    "workspaces": [
    {
      "name": "home",
      "watchlist": ["gme"],
      "components": [
        {
          "type": "quote",
          "yxhw": [0, 0, 8, 3],
          "symbol": "gme",
          "pollMs": 1500

        },
                {
          "type": "list",
          "chartType": "line",
          "yxhw": [8, 0, 4, 3],
          "color": [230, 100, 200],
          "listTypes": [
            "mostactive",
            "gainers"]
        },
        {
          "type": "chart",
          "chartType": "line",
          "yxhw": [0, 3, 12, 9],
          "symbol": "gme",
          "time": "60min",
          "vol": true,
          "color": "green"
                  }
      ]
    },
    {
      "name": "home2",
      "watchlist": ["gsat"],
      "components": [
        {
          "type": "quote",
          "yxhw": [0, 0, 12, 3],
          "symbol": "gsat"
          
        },
                {
          "type": "list",
          "chartType": "line",
          "yxhw": [8, 0, 4, 3],
          "color": [230, 100, 200],
          "listTypes": [
            "mostactive",
            "gainers"
            ]
         
        },
        {
          "type": "chart",
          "chartType": "line",
          "yxhw": [0, 3, 12, 9],
          "symbol": "gsat",
          "time": "60min",
          "vol": true,
          "color": "green"
    
        }
      ]
    },
    
    {
      "name": "home3",
      "watchlist": ["clne"],
      "components": [
        {
          "type": "quote",
          "yxhw": [0, 0, 12, 3],
          "symbol": "clne"
    
        },
                {
          "type": "list",
          "chartType": "line",
          "yxhw": [8, 0, 4, 3],
          "color": [230, 100, 200],
          "listTypes": [
            "mostactive",
            "gainers"
            ]
    
        },
        {
          "type": "chart",
          "chartType": "line",
          "yxhw": [0, 3, 12, 9],
          "symbol": "clne",
          "time": "60min",
          "vol": true,
          "color": "green"
}
      ]
    }
  ]
  
}

```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Konsole
 - Shell: fish

**Additional context**

Thank you so much for this project.

**Comment by arch-btw** [comment]
Thank you so much for this project.

**Comment by HP4k1h5** [comment]
thanks a lot for the support and the bug report! 
this should be resolved in the latest push.

depending on how you downloaded it, you'll want to pull latest or run something like `yarn global update` 

check that your version is `@hp4k1h5/agora@0.1.5`

thanks again.

**Comment by arch-btw** [comment]
Wow that was super fast @HP4k1h5 thank you so much!

I really love this project, I use it every day.
